### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by shepherd-06** [joshuajharris/alfred-medium-workflow#6]
Hey Josh
Great work. I am actually looking for a way to integrate the medium search on my messenger bot. Did u use any medium api? How did u get the search result in json from medium?

Thanks. 👍

**Comment by shepherd-06** [comment]
Hey
I have managed to get json formatted data from medium but I cannot find any way to link them to the exact webpage. Did u work on that?

**Comment by joshuajharris** [comment]
Hey @ibtehaz-shawon, as long as you got the proper json object you're good to go. I used the base url `medium.com` and passed the query parameters `q=QUERY+TEXT&format=json`.

The response that is returned must be formatted, there is extra text at the beginning that looks like `])}while(1);</x>`, which is used to prevent json hijacking.

Once formatted you'll see a `payload.references.Post` object (example below).
![screenshot-20171124172740-360x274](https://user-images.githubusercontent.com/10967744/33224917-dab51676-d13c-11e7-8b84-71e406a608f9.png)
`Post` is a map, with each key being the id of a post. The value has many properties such as `title` or `virtuals.tags`.

The post id is all you need. simply append the post id to the base url like this.
`"https://medium.com/posts/" + POST_ID`

That will give you a link to that exact post.

Good luck :+1:

**Comment by shepherd-06** [comment]
Hey @joshuajharris 
Thanks 👍 
I found it on your code and added it on my project. It's working smooth. 
Good day 👍
